// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnyeeGEu8MKr7E5fferdsSRKZAtppIJcE',
    appId: '1:557763112881:web:86d5da2d9fc0a8b0355790',
    messagingSenderId: '557763112881',
    projectId: 'fir-integration-ee522',
    authDomain: 'fir-integration-ee522.firebaseapp.com',
    storageBucket: 'fir-integration-ee522.firebasestorage.app',
    measurementId: 'G-QD9246L8C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUDAJTImB9BPpfmI9Pg4AfvP_bmRxs050',
    appId: '1:557763112881:android:c59f8fa4a2a95669355790',
    messagingSenderId: '557763112881',
    projectId: 'fir-integration-ee522',
    storageBucket: 'fir-integration-ee522.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIEsZRMJFqHXRAMMFYzsOKXOHIWBcNjRI',
    appId: '1:557763112881:ios:44a8b8b44285b88b355790',
    messagingSenderId: '557763112881',
    projectId: 'fir-integration-ee522',
    storageBucket: 'fir-integration-ee522.firebasestorage.app',
    iosBundleId: 'com.example.deepEmotionsWithBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIEsZRMJFqHXRAMMFYzsOKXOHIWBcNjRI',
    appId: '1:557763112881:ios:44a8b8b44285b88b355790',
    messagingSenderId: '557763112881',
    projectId: 'fir-integration-ee522',
    storageBucket: 'fir-integration-ee522.firebasestorage.app',
    iosBundleId: 'com.example.deepEmotionsWithBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnyeeGEu8MKr7E5fferdsSRKZAtppIJcE',
    appId: '1:557763112881:web:9b84412de2bfb31e355790',
    messagingSenderId: '557763112881',
    projectId: 'fir-integration-ee522',
    authDomain: 'fir-integration-ee522.firebaseapp.com',
    storageBucket: 'fir-integration-ee522.firebasestorage.app',
    measurementId: 'G-2TDZMKR9Q0',
  );

}