// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP3sg7ff-I95nvhgKOTSU3rV6O_3I2Zx0',
    appId: '1:924599384579:web:1b1d3455061f146317ac36',
    messagingSenderId: '924599384579',
    projectId: 'fir-first-ff98b',
    authDomain: 'fir-first-ff98b.firebaseapp.com',
    storageBucket: 'fir-first-ff98b.firebasestorage.app',
    measurementId: 'G-25HT18C6N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUDAJTImB9BPpfmI9Pg4AfvP_bmRxs050',
    appId: '1:557763112881:android:c59f8fa4a2a95669355790',
    messagingSenderId: '557763112881',
    projectId: 'fir-integration-ee522',
    storageBucket: 'fir-integration-ee522.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw6YLeunUciX9Q-PjjMmxptS0XUrhkv-k',
    appId: '1:924599384579:ios:e72034945da209ba17ac36',
    messagingSenderId: '924599384579',
    projectId: 'fir-first-ff98b',
    storageBucket: 'fir-first-ff98b.firebasestorage.app',
    iosClientId:
        '924599384579-fdgkqlcaet67cemtgsuvtuulcl5n4kpt.apps.googleusercontent.com',
    iosBundleId: 'com.elabdtech.deepEmotionsWithBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw6YLeunUciX9Q-PjjMmxptS0XUrhkv-k',
    appId: '1:924599384579:ios:e72034945da209ba17ac36',
    messagingSenderId: '924599384579',
    projectId: 'fir-first-ff98b',
    storageBucket: 'fir-first-ff98b.firebasestorage.app',
    iosClientId:
        '924599384579-fdgkqlcaet67cemtgsuvtuulcl5n4kpt.apps.googleusercontent.com',
    iosBundleId: 'com.elabdtech.deepEmotionsWithBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP3sg7ff-I95nvhgKOTSU3rV6O_3I2Zx0',
    appId: '1:924599384579:web:eb3890329f3cb80317ac36',
    messagingSenderId: '924599384579',
    projectId: 'fir-first-ff98b',
    authDomain: 'fir-first-ff98b.firebaseapp.com',
    storageBucket: 'fir-first-ff98b.firebasestorage.app',
    measurementId: 'G-D1GPRWWHDX',
  );
}
